import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import TanStackProvider from "../providers/TanStackProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LocaleProvider } from "../context/LangContext";
import "../globals.css";
import { ReactNode } from "react";
import NextAuthProvider from "../providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; // Explicitly type children
  params: {
    locale: string; // Define the type for locale
  };
}

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      {/* TODO:remove suppressHydrationWarning={true} */}
      <NextIntlClientProvider messages={messages}>
        <body suppressHydrationWarning={false} className={inter.className}>
          <LocaleProvider locale={locale}>
            <TanStackProvider>
              <NextAuthProvider>
                <div>{children}</div>
              </NextAuthProvider>
            </TanStackProvider>
          </LocaleProvider>
          <Toaster position="top-right" reverseOrder={false} />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
